In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df=pd.read_csv("../Datasets/CoffeeShopSales-cleaned (1).csv")

In [4]:
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount,week,weekday,transaction_hour
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,2022-12-26/2023-01-01,Sunday,7
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,2022-12-26/2023-01-01,Sunday,7
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,2022-12-26/2023-01-01,Sunday,7
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,2022-12-26/2023-01-01,Sunday,7
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,2022-12-26/2023-01-01,Sunday,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,2023-06-26/2023-07-02,Friday,20
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,2023-06-26/2023-07-02,Friday,20
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,2023-06-26/2023-07-02,Friday,20
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,2023-06-26/2023-07-02,Friday,20
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,2023-06-26/2023-07-02,Friday,20

In [106]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail',
       'total_amount', 'week', 'weekday', 'transaction_hour'],
      dtype='object')

In [107]:
df.dtypes

transaction_id        int64
transaction_date     object
transaction_time     object
transaction_qty       int64
store_id              int64
store_location       object
product_id            int64
unit_price          float64
product_category     object
product_type         object
product_detail       object
total_amount        float64
week                 object
weekday              object
transaction_hour      int64
dtype: object

In [108]:
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount,week,weekday,transaction_hour
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,2022-12-26/2023-01-01,Sunday,7
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,2022-12-26/2023-01-01,Sunday,7
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,2022-12-26/2023-01-01,Sunday,7
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,2022-12-26/2023-01-01,Sunday,7
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,2022-12-26/2023-01-01,Sunday,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,2023-06-26/2023-07-02,Friday,20
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,2023-06-26/2023-07-02,Friday,20
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,2023-06-26/2023-07-02,Friday,20
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,2023-06-26/2023-07-02,Friday,20
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,2023-06-26/2023-07-02,Friday,20

In [109]:
df=df.drop('week',axis=1)

In [110]:
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount,weekday,transaction_hour
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,Sunday,7
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,Sunday,7
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,Sunday,7
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,Sunday,7
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,Sunday,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,Friday,20
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,Friday,20
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,Friday,20
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,Friday,20
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,Friday,20

In [111]:
df['Month'] = df.transaction_date.str[-5:-3]

In [112]:
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount,weekday,transaction_hour,Month
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,Sunday,7,01
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,Sunday,7,01
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,Sunday,7,01
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,Sunday,7,01
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,Sunday,7,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,Friday,20,06
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,Friday,20,06
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,Friday,20,06
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,Friday,20,06
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,Friday,20,06

In [113]:
df.transaction_date=df.transaction_date.astype('datetime64[ns]')
df.transaction_time=df.transaction_time.astype('datetime64[ns]')

In [114]:
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount,weekday,transaction_hour,Month
0,1,2023-01-01,2026-06-29 07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,Sunday,7,01
1,2,2023-01-01,2026-06-29 07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,Sunday,7,01
2,3,2023-01-01,2026-06-29 07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,Sunday,7,01
3,4,2023-01-01,2026-06-29 07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,Sunday,7,01
4,5,2023-01-01,2026-06-29 07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,Sunday,7,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,2026-06-29 20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,Friday,20,06
149112,149453,2023-06-30,2026-06-29 20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,Friday,20,06
149113,149454,2023-06-30,2026-06-29 20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,Friday,20,06
149114,149455,2023-06-30,2026-06-29 20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,Friday,20,06
149115,149456,2023-06-30,2026-06-29 20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,Friday,20,06

In [115]:
df.dtypes

transaction_id               int64
transaction_date    datetime64[ns]
transaction_time    datetime64[ns]
transaction_qty              int64
store_id                     int64
store_location              object
product_id                   int64
unit_price                 float64
product_category            object
product_type                object
product_detail              object
total_amount               float64
weekday                     object
transaction_hour             int64
Month                       object
dtype: object

In [116]:
df.store_location.unique()

array(['Lower Manhattan', "Hell's Kitchen", 'Astoria'], dtype=object)

In [117]:
df.product_category.unique()

array(['Coffee', 'Tea', 'Drinking Chocolate', 'Bakery', 'Flavours',
       'Loose Tea', 'Coffee beans', 'Packaged Chocolate', 'Branded'],
      dtype=object)

In [118]:
df.product_type.unique()

array(['Gourmet brewed coffee', 'Brewed Chai tea', 'Hot chocolate',
       'Drip coffee', 'Scone', 'Barista Espresso', 'Brewed Black tea',
       'Brewed Green tea', 'Brewed herbal tea', 'Biscotti', 'Pastry',
       'Organic brewed coffee', 'Premium brewed coffee', 'Regular syrup',
       'Herbal tea', 'Gourmet Beans', 'Organic Beans', 'Sugar free syrup',
       'Drinking Chocolate', 'Premium Beans', 'Chai tea', 'Green beans',
       'Espresso Beans', 'Green tea', 'Organic Chocolate', 'Housewares',
       'Black tea', 'House blend Beans', 'Clothing'], dtype=object)

In [119]:
df.product_detail.unique()

array(['Ethiopia Rg', 'Spicy Eye Opener Chai Lg', 'Dark chocolate Lg',
       'Our Old Time Diner Blend Sm', 'Oatmeal Scone',
       'Columbian Medium Roast Sm', 'Latte Rg', 'Dark chocolate Rg',
       'Spicy Eye Opener Chai Rg', 'Ethiopia Lg', 'Earl Grey Lg',
       'Ouro Brasileiro shot', 'Serenity Green Tea Lg',
       'Jumbo Savory Scone', 'Lemon Grass Rg',
       'Sustainably Grown Organic Lg', 'Hazelnut Biscotti', 'Cappuccino',
       'Lemon Grass Lg', 'Chocolate Chip Biscotti', 'Peppermint Lg',
       'Chocolate Croissant', 'Latte', 'Brazilian Rg', 'Brazilian Lg',
       'Columbian Medium Roast Rg', 'Morning Sunrise Chai Rg',
       'Morning Sunrise Chai Lg', 'Our Old Time Diner Blend Lg',
       'Sustainably Grown Organic Rg', 'Scottish Cream Scone ',
       'Peppermint Rg', 'English Breakfast Rg',
       'Our Old Time Diner Blend Rg', 'Serenity Green Tea Rg',
       'Brazilian Sm', 'Jamaican Coffee River Sm',
       'Jamaican Coffee River Lg', 'Ginger Biscotti',
       'Traditional Blend Chai Lg', 'Cappuccino Lg', 'Espresso shot',
       'Earl Grey Rg', 'Ginger Scone', 'Jamaican Coffee River Rg',
       'Cranberry Scone', 'Almond Croissant', 'Croissant', 'Ethiopia Sm',
       'English Breakfast Lg', 'Traditional Blend Chai Rg',
       'Columbian Medium Roast Lg', 'Hazelnut syrup', 'Peppermint',
       'Carmel syrup', 'Ethiopia', 'Organic Decaf Blend',
       'Sugar Free Vanilla syrup', 'Chocolate syrup', 'Dark chocolate',
       'Jamacian Coffee River', 'Brazilian - Organic',
       'Morning Sunrise Chai', 'Guatemalan Sustainably Grown',
       'Primo Espresso Roast', 'Serenity Green Tea',
       'Traditional Blend Chai', 'Espresso Roast',
       'Sustainably Grown Organic', 'I Need My Bean! Latte cup',
       'Spicy Eye Opener Chai', 'Chili Mayan', 'English Breakfast',
       'Lemon Grass', 'Columbian Medium Roast',
       'Our Old Time Diner Blend', 'I Need My Bean! T-shirt', 'Earl Grey',
       'Civet Cat', 'I Need My Bean! Diner mug'], dtype=object)

In [120]:
df.dtypes

transaction_id               int64
transaction_date    datetime64[ns]
transaction_time    datetime64[ns]
transaction_qty              int64
store_id                     int64
store_location              object
product_id                   int64
unit_price                 float64
product_category            object
product_type                object
product_detail              object
total_amount               float64
weekday                     object
transaction_hour             int64
Month                       object
dtype: object

In [121]:
df.product_detail.value_counts()

product_detail
Chocolate Croissant             3076
Earl Grey Rg                    3053
Dark chocolate Lg               3029
Morning Sunrise Chai Rg         3026
Columbian Medium Roast Rg       3013
                                ...
Jamacian Coffee River            146
Earl Grey                        142
Guatemalan Sustainably Grown     134
Spicy Eye Opener Chai            122
Dark chocolate                   118
Name: count, Length: 80, dtype: int64

In [122]:
df.product_type.value_counts()

product_type
Brewed Chai tea          17183
Gourmet brewed coffee    16912
Barista Espresso         16403
Hot chocolate            11468
Brewed Black tea         11350
Brewed herbal tea        11245
Scone                    10173
Organic brewed coffee     8489
Drip coffee               8477
Premium brewed coffee     8135
Pastry                    6912
Biscotti                  5711
Brewed Green tea          5671
Regular syrup             4979
Sugar free syrup          1811
Housewares                 526
Chai tea                   443
Organic Beans              415
Gourmet Beans              366
Premium Beans              336
Espresso Beans             319
Herbal tea                 305
Black tea                  303
Drinking Chocolate         266
Organic Chocolate          221
Clothing                   221
House blend Beans          183
Green tea                  159
Green beans                134
Name: count, dtype: int64

In [123]:
df.store_location.value_counts()

store_location
Hell's Kitchen     50735
Astoria            50599
Lower Manhattan    47782
Name: count, dtype: int64

In [124]:
df.product_type.value_counts()

product_type
Brewed Chai tea          17183
Gourmet brewed coffee    16912
Barista Espresso         16403
Hot chocolate            11468
Brewed Black tea         11350
Brewed herbal tea        11245
Scone                    10173
Organic brewed coffee     8489
Drip coffee               8477
Premium brewed coffee     8135
Pastry                    6912
Biscotti                  5711
Brewed Green tea          5671
Regular syrup             4979
Sugar free syrup          1811
Housewares                 526
Chai tea                   443
Organic Beans              415
Gourmet Beans              366
Premium Beans              336
Espresso Beans             319
Herbal tea                 305
Black tea                  303
Drinking Chocolate         266
Organic Chocolate          221
Clothing                   221
House blend Beans          183
Green tea                  159
Green beans                134
Name: count, dtype: int64

In [125]:
df.product_detail.value_counts()

product_detail
Chocolate Croissant             3076
Earl Grey Rg                    3053
Dark chocolate Lg               3029
Morning Sunrise Chai Rg         3026
Columbian Medium Roast Rg       3013
                                ...
Jamacian Coffee River            146
Earl Grey                        142
Guatemalan Sustainably Grown     134
Spicy Eye Opener Chai            122
Dark chocolate                   118
Name: count, Length: 80, dtype: int64

In [126]:
df.describe()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,product_id,unit_price,total_amount,transaction_hour
count,149116.000000,149116,149116,149116.000000,149116.000000,149116.000000,149116.000000,149116.000000,149116.000000
mean,74737.371872,2023-04-15 11:50:32.173609984,2026-06-29 12:14:15.815794688,1.438276,5.342063,47.918607,3.382219,4.686367,11.735790
min,1.000000,2023-01-01 00:00:00,2026-06-29 06:00:00,1.000000,3.000000,1.000000,0.800000,0.800000,6.000000
25%,37335.750000,2023-03-06 00:00:00,2026-06-29 09:05:10.500000,1.000000,3.000000,33.000000,2.500000,3.000000,9.000000
50%,74727.500000,2023-04-24 00:00:00,2026-06-29 11:15:28,1.000000,5.000000,47.000000,3.000000,3.750000,11.000000
75%,112094.250000,2023-05-30 00:00:00,2026-06-29 15:25:57,2.000000,8.000000,60.000000,3.750000,6.000000,15.000000
max,149456.000000,2023-06-30 00:00:00,2026-06-29 20:59:32,8.000000,8.000000,87.000000,45.000000,360.000000,20.000000
std,43153.600016,NaN,NaN,0.542509,2.074241,17.930020,2.658723,4.227099,3.764662

In [127]:
df.corr(numeric_only='true')

,transaction_id,transaction_qty,store_id,product_id,unit_price,total_amount,transaction_hour
transaction_id,1.000000,0.010250,-0.006054,0.001076,0.000836,0.005949,-0.012488
transaction_qty,0.010250,1.000000,-0.000794,-0.175255,-0.123546,0.356231,-0.006310
store_id,-0.006054,-0.000794,1.000000,0.025727,0.001891,0.004595,-0.075813
product_id,0.001076,-0.175255,0.025727,1.000000,-0.140423,-0.167461,-0.031644
unit_price,0.000836,-0.123546,0.001891,-0.140423,1.000000,0.685550,-0.018435
total_amount,0.005949,0.356231,0.004595,-0.167461,0.685550,1.000000,-0.013783
transaction_hour,-0.012488,-0.006310,-0.075813,-0.031644,-0.018435,-0.013783,1.000000

In [128]:
df.groupby('store_location')['total_amount'].sum()

store_location
Astoria            232243.91
Hell's Kitchen     236511.17
Lower Manhattan    230057.25
Name: total_amount, dtype: float64

In [70]:
df.groupby('Month')['total_amount'].sum()

Month
01     81677.74
02     76145.19
03     98834.68
04    118941.08
05    156727.76
06    166485.88
Name: total_amount, dtype: float64

In [73]:
df.groupby('product_category')['total_amount'].sum()

product_category
Bakery                 82315.64
Branded                13607.00
Coffee                269952.45
Coffee beans           40085.25
Drinking Chocolate     72416.00
Flavours                8408.80
Loose Tea              11213.60
Packaged Chocolate      4407.64
Tea                   196405.95
Name: total_amount, dtype: float64

In [74]:
df.groupby('product_category')['total_amount'].sum().nlargest(5)

product_category
Coffee                269952.45
Tea                   196405.95
Bakery                 82315.64
Drinking Chocolate     72416.00
Coffee beans           40085.25
Name: total_amount, dtype: float64

In [76]:
df.groupby('product_type')['total_amount'].sum().nlargest(10)

product_type
Barista Espresso         91406.20
Brewed Chai tea          77081.95
Hot chocolate            72416.00
Gourmet brewed coffee    70034.60
Brewed Black tea         47932.00
Brewed herbal tea        47539.50
Premium brewed coffee    38781.15
Organic brewed coffee    37746.50
Scone                    36866.12
Drip coffee              31984.00
Name: total_amount, dtype: float64

In [77]:
df.groupby('product_type')['transaction_qty'].sum().nlargest(10)

product_type
Brewed Chai tea          26250
Gourmet brewed coffee    25973
Barista Espresso         24943
Brewed Black tea         17462
Hot chocolate            17457
Brewed herbal tea        17328
Organic brewed coffee    13012
Drip coffee              12891
Premium brewed coffee    12431
Scone                    10465
Name: transaction_qty, dtype: int64

In [78]:
df.groupby('product_type')['transaction_qty'].sum().nsmallest(10)

product_type
Green beans           134
Green tea             159
House blend Beans     183
Clothing              221
Organic Chocolate     221
Drinking Chocolate    266
Black tea             303
Herbal tea            305
Espresso Beans        319
Gourmet Beans         366
Name: transaction_qty, dtype: int64

In [83]:
df.groupby('weekday')['total_amount'].mean()

weekday
Friday       4.671352
Monday       4.697929
Saturday     4.724255
Sunday       4.661088
Thursday     4.653541
Tuesday      4.690875
Wednesday    4.707346
Name: total_amount, dtype: float64

In [ ]:
total_amount

In [82]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail',
       'total_amount', 'weekday', 'transaction_hour', 'Month'],
      dtype='object')

In [94]:
pd.pivot_table(df,index='store_location',columns='product_category',values='total_amount',aggfunc='sum',margins=True)

product_category,Bakery,Branded,Coffee,Coffee beans,Drinking Chocolate,Flavours,Loose Tea,Packaged Chocolate,Tea,All
store_location,,,,,,,,,,
Astoria,26599.75,5457.0,89744.30,10219.20,26335.25,1764.8,3194.00,1089.71,67839.90,232243.91
Hell's Kitchen,27386.95,1942.0,91222.65,18635.10,23586.25,2876.8,4461.35,1698.77,64701.30,236511.17
Lower Manhattan,28328.94,6208.0,88985.50,11230.95,22494.50,3767.2,3558.25,1619.16,63864.75,230057.25
All,82315.64,13607.0,269952.45,40085.25,72416.00,8408.8,11213.60,4407.64,196405.95,698812.33

In [95]:
pd.pivot_table(df,index='weekday',columns='store_location',values='total_amount',aggfunc='sum',margins=True)

store_location    Astoria  Hell's Kitchen  Lower Manhattan        All
weekday
Friday           33472.75        34743.18         33157.07  101373.00
Monday           33928.29        33389.51         34359.48  101677.28
Saturday         31845.93        32599.23         32449.32   96894.48
Sunday           32795.18        33685.63         31849.50   98330.31
Thursday         34140.37        33468.06         33159.35  100767.78
Tuesday          31816.76        34846.47         32792.71   99455.94
Wednesday        34244.63        33779.09         32289.82  100313.54
All             232243.91       236511.17        230057.25  698812.33

In [96]:
pd.pivot_table(df,index='product_type',columns='product_category',values='transaction_qty',aggfunc='sum',margins=True)

product_category,Bakery,Branded,Coffee,Coffee beans,Drinking Chocolate,Flavours,Loose Tea,Packaged Chocolate,Tea,All
product_type,,,,,,,,,,
Barista Espresso,NaN,NaN,24943.0,NaN,NaN,NaN,NaN,NaN,NaN,24943
Biscotti,5788.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5788
Black tea,NaN,NaN,NaN,NaN,NaN,NaN,303.0,NaN,NaN,303
Brewed Black tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17462.0,17462
Brewed Chai tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26250.0,26250
Brewed Green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8697.0,8697
Brewed herbal tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17328.0,17328
Chai tea,NaN,NaN,NaN,NaN,NaN,NaN,443.0,NaN,NaN,443
Clothing,NaN,221.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,221
Drinking Chocolate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,266.0,NaN,266
Drip coffee,NaN,NaN,12891.0,NaN,NaN,NaN,NaN,NaN,NaN,12891
Espresso Beans,NaN,NaN,NaN,319.0,NaN,NaN,NaN,NaN,NaN,319
Gourmet Beans,NaN,NaN,NaN,366.0,NaN,NaN,NaN,NaN,NaN,366
Gourmet brewed coffee,NaN,NaN,25973.0,NaN,NaN,NaN,NaN,NaN,NaN,25973
Green beans,NaN,NaN,NaN,134.0,NaN,NaN,NaN,NaN,NaN,134
Green tea,NaN,NaN,NaN,NaN,NaN,NaN,159.0,NaN,NaN,159
Herbal tea,NaN,NaN,NaN,NaN,NaN,NaN,305.0,NaN,NaN,305
Hot chocolate,NaN,NaN,NaN,NaN,17457.0,NaN,NaN,NaN,NaN,17457
House blend Beans,NaN,NaN,NaN,183.0,NaN,NaN,NaN,NaN,NaN,183
Housewares,NaN,555.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,555
Organic Beans,NaN,NaN,NaN,420.0,NaN,NaN,NaN,NaN,NaN,420
Organic Chocolate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,221.0,NaN,221
Organic brewed coffee,NaN,NaN,13012.0,NaN,NaN,NaN,NaN,NaN,NaN,13012
Pastry,6961.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6961
Premium Beans,NaN,NaN,NaN,406.0,NaN,NaN,NaN,NaN,NaN,406
Premium brewed coffee,NaN,NaN,12431.0,NaN,NaN,NaN,NaN,NaN,NaN,12431
Regular syrup,NaN,NaN,NaN,NaN,NaN,7606.0,NaN,NaN,NaN,7606
Scone,10465.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10465
Sugar free syrup,NaN,NaN,NaN,NaN,NaN,2905.0,NaN,NaN,NaN,2905
All,23214.0,776.0,89250.0,1828.0,17457.0,10511.0,1210.0,487.0,69737.0,214470

In [97]:
pd.pivot_table(df,index='Month',columns='product_category',values='transaction_qty',aggfunc='sum',margins=True)

product_category,Bakery,Branded,Coffee,Coffee beans,Drinking Chocolate,Flavours,Loose Tea,Packaged Chocolate,Tea,All
Month,,,,,,,,,,
01,2690,100,10355,234,2015,1218,141,57,8060,24870
02,2559,74,9689,195,1964,1163,137,51,7718,23550
03,3358,104,12604,251,2475,1465,178,65,9906,30406
04,3951,142,15210,310,2952,1773,197,95,11839,36469
05,5225,161,19948,407,3930,2382,259,108,15813,48233
06,5431,195,21444,431,4121,2510,298,111,16401,50942
All,23214,776,89250,1828,17457,10511,1210,487,69737,214470

In [98]:
#dashboard

In [ ]:
print(df.store_location.unique())
s=input("enter store_location:")
strr =df[df.store_location==s]

print(strr.product_category.unique())
p=input("enter product_category:")
pro=strr[strr.product_category==p]

t = pro.groupby('product_type')['total_amount'].sum()
sb.barplot(x=t.index,y=t.values)
plt.xticks(rotation=90)
plt.show()

['Lower Manhattan' "Hell's Kitchen" 'Astoria']